# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  test_push:
    name: Test on push
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.ref == 'refs/heads/master' && '0' || '1' }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i

      - name: Run tests
        run: npm run test:cov

      - name: Codeclimate
        if: github.ref == 'refs/heads/master'
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov

      - name: Semantic Release
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PROVENANCE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
        run: npm_config_yes=true npx zx-semrel

  pr_node:
    if: ${{ github.event_name == 'pull_request' }}
    name: Test PR (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        node-version: [ 16, 20 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: npm i

      - if: matrix.os == 'windows-2019'
        run: npm i -g npm

      - name: Run tests
        timeout-minutes: 2
        run: npm test

  pr_bun:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-22.04
    name: PR with Bun
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1

      - name: Deps
        run: |
          bun install
          ln -s ../ ./node_modules/zx-extra

      - name: Run tests
        timeout-minutes: 2
        run: bun test:bun
